### ISSUE TITLE
Command to open the command palette

### ISSUE THREAD

**Issue by miroswd** [joaopcm/nodepad#17]
**Is your feature request related to a problem? Please describe.**
I use linux so I don't have the command key

**Describe the solution you'd like**
Change command key to forward slash /

**Describe alternatives you've considered**
Could create a right click box to use commands

**Additional context**
![image](https://user-images.githubusercontent.com/54915150/227206626-7935d4ab-0d52-48b9-927b-6ee5422af806.png)

**Comment by miroswd** [comment]
In my case when I press `ctrl+k` it has no effect. I tried using various combinations like `ctrl+alt`, `alt gr`, etc. But the solution you proposed seems fine to me.

**Comment by joaopcm** [comment]
You are probably trying to use the shortcut (control + K) while having your courses focused on a text or code. To use shortcuts, you need to focus on elements that are not part of the note.

I tested it on other computers and was able to use the shortcuts. Can you verify that the problem is that your cursor is focused on some text block or code snippet?

**Comment by danielsitnik** [comment]
Hmmm this is currently very unintuitive in my opinion.
I'm used to Atlassian Confluence, so I was under the impression that I had to press `cmd+K` and then select something like the `code snippet` to insert it into the document.

After some fiddling I realized I only needed to type ` ``` ` to get a code block.

**Comment by joaopcm** [comment]
> Hmmm this is currently very unintuitive in my opinion. I'm used to Atlassian Confluence, so I was under the impression that I had to press `cmd+K` and then select the `code snippet` widget from some kind of library to insert it into the document.
> 
> After some fiddling I realized I only needed to type `` ``` `` to get a code block.

@danielsitnik, thank you for your input! I believe that this is another problem. This issue is regarding the shortcuts not being accessible when typing. I just opened a PR ⬆️ fixing it.

If you have an idea of how to improve and make Nodepad more intuitive, please one a new issue 😃 Nodepad is based on Markdown, so there's no `code snippet` widget from some kind of library to insert into the document. It's just the ``` to open a code block section, as you'd do using Markdown.

It'd be great if we had some shortcuts in the command palette to insert some blocks into the document. Please feel free to create an issue so that someone can work on that :)

**Comment by joaopcm** [comment]
@miroswd, just opened [this PR](https://github.com/joaopcm/nodepad/pull/22) to fix your problems. After it gets merged, it must work for you ;)
